<a href="https://colab.research.google.com/github/Shadhin282/Machine-learning-problem-Solving/blob/main/knn_for_Regression_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [49]:
dict_ = {
    "Age" : [21,20,22,22,23,21,25,30,31],
    "Income(K)" : [60,55,60,61,65,62,65,70,68]
}

In [50]:
df = pd.DataFrame(dict_)

In [51]:
df

Age  Income(K)
0   21         60
1   20         55
2   22         60
3   22         61
4   23         65
5   21         62
6   25         65
7   30         70
8   31         68

In [52]:
x = df[["Age"]]
x

Age
0   21
1   20
2   22
3   22
4   23
5   21
6   25
7   30
8   31

In [53]:
y = df[['Income(K)']]
y


Income(K)
0         60
1         55
2         60
3         61
4         65
5         62
6         65
7         70
8         68

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
reg = LinearRegression()
reg

LinearRegression()

In [10]:
reg.fit(x,y)

LinearRegression()

In [11]:
reg.score(x,y)

0.7870258620689656

In [12]:
from sklearn.metrics import mean_squared_error , r2_score

In [15]:
predict = reg.predict(x)

In [16]:
mean_squared_error(y,predict)

3.9965517241379303

In [17]:
r2_score(y,predict)

0.7870258620689656

In [22]:
m = reg.coef_
m

array([[1.01551724]])

In [23]:
c = reg.intercept_
c

array([38.62931034])

In [28]:
y_pred = m * 22 + c
y_pred

array([[60.97068966]])

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

In [67]:
reg_1 = KNeighborsRegressor(n_neighbors = 3)
reg_1

KNeighborsRegressor(n_neighbors=3)

In [68]:
reg_1.fit(x,y)

KNeighborsRegressor(n_neighbors=3)

In [69]:
reg_1.predict(x)

array([[59.        ],
       [59.        ],
       [60.33333333],
       [60.33333333],
       [62.        ],
       [59.        ],
       [63.33333333],
       [67.66666667],
       [67.66666667]])

In [70]:
reg_1.predict([[22]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


array([[60.33333333]])

In [71]:
reg_1.score(x,y)

0.7401315789473687

In [72]:
r2_score(y,reg_1.predict(x))

0.7401315789473687

In [73]:
mean_squared_error(y,reg_1.predict(x))

4.876543209876539