<a href="https://colab.research.google.com/github/Shadhin282/Machine-learning-problem-Solving/blob/main/KNN_Assessment(1_%26_2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
import pandas as pd
import warnings as wr
wr.filterwarnings('ignore')

In [73]:
df = pd.read_csv('/weight-height.csv')
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [74]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [75]:
df.Gender = le.fit_transform(df[['Gender']])

In [76]:
df.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [77]:
df.tail()

Gender     Height      Weight
8550       0  60.483946  110.565497
8551       0  63.423372  129.921671
8552       0  65.584057  155.942671
8553       0  67.429971  151.678405
8554       0  60.921791  131.253738

# Go Ahead

In [78]:
x = df.drop(columns=['Weight'])
y = df[['Weight']]
x.head()

Gender     Height
0       1  73.847017
1       1  68.781904
2       1  74.110105
3       1  71.730978
4       1  69.881796

In [79]:
y.head()

Weight
0  241.893563
1  162.310473
2  212.740856
3  220.042470
4  206.349801

In [80]:
from sklearn.linear_model import LinearRegression

In [81]:
lr = LinearRegression()

In [82]:
from sklearn.model_selection import train_test_split

In [83]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.30,random_state=0)

In [84]:
xtrain.shape

(5988, 2)

In [85]:
ytrain.shape

(5988, 1)

In [86]:
lr.fit(xtrain,ytrain)

LinearRegression()

In [87]:
lr.score(xtest,ytest)

0.9025307579174771

In [88]:
lr.score(xtrain,ytrain)

0.8988118427483529

In [89]:
from sklearn.metrics import mean_squared_error

In [90]:
predict = lr.predict(xtest)
predict[0:5]

array([[156.20235428],
       [184.93442898],
       [148.42945323],
       [150.77947019],
       [176.60175571]])

In [91]:
ytest.head()

Weight
541   174.473363
3209  178.507500
7598  155.248900
5170  138.839940
2423  154.718344

In [92]:
mean_squared_error(ytest,predict)

102.30154155088874

In [93]:
from sklearn.metrics import r2_score

In [94]:
r2_score(ytest,predict)

0.9025307579174771

In [95]:
from sklearn.neighbors import KNeighborsRegressor

In [96]:
knn = KNeighborsRegressor(n_neighbors = 21)
knn

KNeighborsRegressor(n_neighbors=21)

In [97]:
knn.fit(xtrain,ytrain)

KNeighborsRegressor(n_neighbors=21)

In [98]:
knn.score(xtest,ytest)

0.8963739079210189

In [99]:
knn.kneighbors_graph(xtest)

<2567x5988 sparse matrix of type '<class 'numpy.float64'>'
	with 53907 stored elements in Compressed Sparse Row format>

In [100]:
knn.predict(xtest)[0:10]

array([[155.93093662],
       [187.30392565],
       [150.75798316],
       [150.66758425],
       [182.66808951],
       [130.20444529],
       [168.97974454],
       [157.5318055 ],
       [137.77646853],
       [184.83200425]])

In [101]:
ytest.head(10)

Weight
541   174.473363
3209  178.507500
7598  155.248900
5170  138.839940
2423  154.718344
6606  119.937293
4097  181.987816
4250  161.015155
7193  120.607958
3429  184.532866

Evaluating The results

In [102]:
knn.score(xtrain,ytrain)


0.9028654156028769

In [103]:
knn.score(xtest,ytest)

0.8963739079210189

In [104]:
lr.score(xtrain,ytrain)

0.8988118427483529

In [105]:
lr.score(xtest,ytest)

0.9025307579174771

In [106]:
mean_squared_error(ytest,predict)

102.30154155088874

In [107]:
mean_squared_error(ytest,knn.predict(xtest))

108.76363392257245

In [108]:
r2_score(ytest,predict)

0.9025307579174771

In [109]:
r2_score(ytest,knn.predict(xtest))

0.8963739079210189

In [110]:
# More error shown at KNN regression model

Work with KNN Classifier

In [111]:
from sklearn.neighbors import KNeighborsClassifier

In [121]:
knnc = KNeighborsClassifier(n_neighbors =21)
knnc

KNeighborsClassifier(n_neighbors=21)

In [117]:
x_c = df.drop(columns=['Gender'])
x_c.head()

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [118]:
y_c = df[['Gender']]
y_c.head()

Gender
0       1
1       1
2       1
3       1
4       1

In [119]:
x_train,x_test,y_train,y_test = train_test_split(x_c,y_c,test_size=0.30,random_state=0)

In [122]:
knnc.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=21)

In [123]:
knnc.score(x_test,y_test)

0.9146864043630697

In [124]:
knnc.predict(x_test)[0:10]

array([1, 1, 0, 0, 0, 0, 1, 1, 0, 1])

In [125]:
y_test.head(10)

Gender
541        1
3209       1
7598       0
5170       0
2423       1
6606       0
4097       1
4250       1
7193       0
3429       1

In [126]:
mean_squared_error(y_test,knnc.predict(x_test))

0.08531359563693026

In [127]:
r2_score(y_test,knnc.predict(x_test))

0.6488464219592087

In [128]:
mean_squared_error(y_train,knnc.predict(x_train))

0.07798931195724783

In [129]:
r2_score(y_train,knnc.predict(x_train))

0.6788331026565217